on: [push, pull_request]
name: CI
jobs:
  ci:
    strategy:
      matrix:
        go-version: [1.19.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v2.1.5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.4.0
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -race -v ./...
