on: [push, pull_request]
name: CI
jobs:
  ci:
    strategy:
      matrix:
        go-version: [1.19.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v2.1.5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v2.4.0
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -race -v ./...
